---
# there is issue with filteing based on name and tags, PR is submitted
# https://github.com/external-secrets/external-secrets/pull/5685
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: app
spec:
  refreshInterval: 1m
  refreshPolicy: Periodic
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: app-k8s-secrets
    immutable: false
  dataFrom:
  - find:
      name:
        regexp: "^RESTRICTED.*"
      tags:
        Cluster: "eks-secrets-example"
