---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxy-secrets
  namespace: proxy
spec:
  refreshInterval: 1m
  refreshPolicy: Periodic
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: proxy-k8s-secrets
    immutable: false
  dataFrom:
    - find:
        name: 
          regexp: "APP.*"
        tags:
          ManagedBy: ip812
