---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: app
spec:
  refreshInterval: 1m
  refreshPolicy: Periodic
  secretStoreRef:
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: some-very-random-cert
    immutable: false
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ .crt }}"
        tls.key: "{{ .key }}"
  dataFrom:
    - extract:
        key: RESTRICTED.playground.TLS_CERTIFICATE.some_very_random_cert
